# Generated by Django 3.0.8 on 2020-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('analyzer', models.CharField(max_length=30)),
            ],
        ),
    ]
